### ISSUE TITLE
Device rotation not supported

### ISSUE THREAD

**Issue by brunoterraaxa** [tungvoduc/DTPhotoViewerController#1]
Don't get me wrong! The lib is AWESOME! but ... the main issue i've found is when you are looking at the image with the controller and rotate your device. This action seems that is not yet supported and is a real cool improvement.

**Comment by tungvoduc** [comment]
@brunoterraaxa : Thanks! I will add support for device rotation.

**Comment by tungvoduc** [comment]
@brunoterraaxa : Sorry for late update. The feature you requested is now available in latest pod. Can you check it?
