### ISSUE TITLE
One cell. CGSize(width: view.frame.width, height: 300)

### ISSUE THREAD

**Issue by sLm-s** [tungvoduc/DTPhotoViewerController#14]
How to apply your method if a collection with one visible image is installed on the screen. For example, when you increase the isolation and after you wind up the collection and stop at the 3 index, after you close the picture and on this day the collection would wind up to the desired index

**Comment by tungvoduc** [comment]
@sLm-s Please check the example project. I implemented exactly what you are describing.

**Comment by tungvoduc** [comment]
@sLm-s Yes this is supported by DTPhotoViewerController. You have to implement this delegate method `photoViewerController(_: DTPhotoViewerController, didScrollToPhotoAt: Int)`. Here is an example:

```swift
// Example
@objc optional func photoViewerController(_ photoViewerController: DTPhotoViewerController, didScrollToPhotoAt index: Int) {
    // Save the current index
    selectedItemIndex = index
}

// Call on viewWillAppear
func scrollToSelectedItemIndex(_ animated: Bool) {
    let indexPath = IndexPath(item: selectedItemIndex, section: 0)
    collectionView.scrollToItem(at: indexPath, at: .centeredVertically, animated: animated)
}
```

**Comment by sLm-s** [comment]
I did not quite understand how to do this. Found a bug when you open the full screen image and scroll to the next index, after making a meek gesture on the drawing back and forth, then there is a sharp update of the picture.

**Comment by tungvoduc** [comment]
@sLm-s Okay, I see. This is not a bug of DTPhotoViewerController. This is a bug in the example. I will check and fix it soon. Thanks.
Do you understand delegate?

**Comment by sLm-s** [comment]
I made the scrolling in this way. But also for this when I click on the picture, then in the back of it the picture blinks from the first index.

Sorry for my bad english


```
func photoViewerController(_ photoViewerController: DTPhotoViewerController, configureCell cell: DTPhotoCollectionViewCell, forPhotoAt index: Int) {
        // Set text for each item
        if let cell = cell as? CustomPhotoCollectionViewCell {
            cell.extraLabel.text = "Index \(index)"
            let indexPath = IndexPath(item: index, section: 0)
            collectionView.scrollToItem(at: indexPath, at: .centeredHorizontally, animated: false)
        }
    }
```

**Comment by tungvoduc** [comment]
@sLm-s This does not work. Follow my first comment, implement delegate method `photoViewerController(_: DTPhotoViewerController, didScrollToPhotoAt: Int)`. Also, do not call `collectionView.scrollToItem(at: indexPath, at: .centeredHorizontally, animated: false)` inside the delegate method because collectionView is likely not visible, so you should store the index and call it after DTPhotoViewerController is dismissed. For the best, call it on `viewWillAppear(_: Bool)`.

**Comment by sLm-s** [comment]
This method is not very cute, the user sees how the collection scrolls.

// Call on viewWillAppear
func scrollToSelectedItemIndex(_ animated: Bool) {
    let indexPath = IndexPath(item: selectedItemIndex, section: 0)
    collectionView.scrollToItem(at: indexPath, at: .centeredVertically, animated: animated)
}

I would like that this all happens is not noticeable for the user

**Comment by sLm-s** [comment]
Thank you very much.
This works well in this way.

`func photoViewerController(_ photoViewerController: DTPhotoViewerController, didScrollToPhotoAt index: Int) {
//        // Save the current index
        let indexPath = IndexPath(item: index, section: 0)
        collectionView.scrollToItem(at: indexPath, at: .centeredHorizontally, animated: false)
    }`

I will wait for an early correction of the example

**Comment by tungvoduc** [comment]
@sLm-s I updated the example. Please check.
