### ISSUE TITLE
There is an issue here.

### ISSUE THREAD

**Issue by eastswift** [tungvoduc/DTPhotoViewerController#16]
There is an issue here.

1. In landscape view on iPhone x, the image is pushed a few pixels to the right.
2. If you rotate the screen after zooming in, the position will not come out properly.

**Comment by tungvoduc** [comment]
@eastswift Sorry for late reply. I've been busy with my company project but now I am back. Anyway, thank you for your report, I just checked and noticed the same issue, I will fix it and release an update  asap.

**Comment by tungvoduc** [comment]
@eastswift I've fixed those issues with new version **1.2.2**. Can you please check and make sure that they are ok now.

**Comment by eastswift** [comment]
It has not been fixed yet. If you turn the image over while zoomed in, the next image will not be displayed. ^^;

**Comment by tungvoduc** [comment]
@eastswift Yes you are right. I will try to fix it as soon as possible.

**Comment by ducnv2910** [comment]
I got this bug also. 

1. Zooming then rotate the device this image will be broken. 
2. Zooming then scroll to next image.

**Comment by tungvoduc** [comment]
@eastswift @ducnv2910 Sorry for late answer. I believe the issue is now completly fixed. Please check latest pod version (3.0.1).
