### ISSUE TITLE
DTPhotoViewerController crashes the application 

### ISSUE THREAD

**Issue by amrit42087** [tungvoduc/DTPhotoViewerController#17]
My application crashes if I use the full size image in the following delegate: 

    func photoViewerController(_ photoViewerController: DTPhotoViewerController, configurePhotoAt 
    index: Int, withImageView imageView: UIImageView) {
         imageView.image = images[index].image
    }

But if I reduce the size of image, the problem is not there. It crashes after I scroll about 50 images. The console says that out of memory. So I think the application is out of memory when I am using heavy images.

**Comment by tungvoduc** [comment]
Sorry for late reply. I've been busy with my company project but now I am back. Anyway, thank you for your report, I will check it and figure out what could be wrong.

**Comment by amrit42087** [comment]
@tungvoduc Did you get time to investigate the issue?

**Comment by tungvoduc** [comment]
@amrit42087 Sorry for getting back so late. I will be maintaining this project more often from now. I just checked it with the demo project and created 100 heavy images, everything works fine. In fact, the photo view controller does not take much memory. Can you check your memory management in your code?
