### ISSUE TITLE
How can i present PhotoLibrary without referenceView

### ISSUE THREAD

**Issue by Alexookah** [tungvoduc/DTPhotoViewerController#23]
I am trying to download from url's some photos and it seems that the referenceView is required.

Is there a way to have optional the referencedView? because sometimes referenceView is not always available
(action from text to open a remote image for example)

(i have subclassed DTPhotoViewerController and added activityIndicator to hide when download completes)

**Comment by tungvoduc** [comment]
Sorry for getting back to this so late. I will be maintaining this project regularly from now on. I will add feature to present photo viewer controller without a reference view.

**Comment by tungvoduc** [comment]
@Alexookah #29 should fix your issue.
