### ISSUE TITLE
Add Caption to each Image?

### ISSUE THREAD

**Issue by Urkman** [tungvoduc/DTPhotoViewerController#3]
Is there a chance to get a caption and a share button to each image?

**Comment by tungvoduc** [comment]
@Urkman You can add buttons or other elements to the controller. In the sample project, I also add a cancel button to it. I am doing a new version that will allow custom view for each individual image.

**Comment by Urkman** [comment]
Thanks... I take a look at the Example 👍

**Comment by cardyng** [comment]
Thank you very much for making this viewer! Like it so much!
