### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by furiosFast** [tungvoduc/DTPhotoViewerController#33]
Hi,
Is it possible to rotate only the photo view page?

thank you

**Comment by tungvoduc** [comment]
Hello, sorry for late reply, just back from my vacation.

What do you mean by ”rotate only photo view page”? I will release new version tomorrow which will fix rotation issue, not sure if you are talking about it.

**Comment by furiosFast** [comment]
hi,
what I mean is something like this:
```
private func rotateImage(){
        NotificationCenter.default.addObserver(forName: UIDevice.orientationDidChangeNotification, object: nil, queue: .main) { (notification) in
            guard var initialImg = self.initialImage else { return }
            UIView.animate(withDuration: 0.5, animations: {
            switch UIDevice.current.orientation {
                case .landscapeLeft: do {
                    super.imageView.transform = CGAffineTransform(rotationAngle: CGFloat(Float.pi/2))                    
                }
                case .landscapeRight: do {
                    initialImg = initialImg.rotate(radians: -Float.pi/2)!
                    super.imageView.image = initialImg
                }
                case .portrait: do {
                    super.imageView.image = initialImg
                }
                case .portraitUpsideDown: do {
                    initialImg = initialImg.rotate(radians: -Float.pi)!
                    super.imageView.image = initialImg
                }
                default: break
            }
            })
        }
    }
```

**Comment by tungvoduc** [comment]
@furiosFast Then you only need to disable rotation for the SimplePhotoViewerController or the app. Take a look at this: https://developer.apple.com/documentation/uikit/uiviewcontroller#//apple_ref/occ/instm/UIViewController/shouldAutorotate

**Comment by furiosFast** [comment]
hi,
in the example app i've add in ViewController
```
override var shouldAutorotate: Bool {
    return false
  }
```
and in SimplePhotoViewerController
```
override var shouldAutorotate: Bool {
    return true
  }
```
but the application continues in both controllers and not only in the one with the photo (SimplePhotoViewerController)

**Comment by mriccasyncpoint** [comment]
try to use:                     
`super.view.transform = CGAffineTransform(rotationAngle: CGFloat(Float.pi/2))`

**Comment by tungvoduc** [comment]
@furiosFast I'll check it later today and get back to you later.

**Comment by furiosFast** [comment]
thank's

**Comment by furiosFast** [comment]
hey hi, do you have any good news?

**Comment by tungvoduc** [comment]
@furiosFast This issue is unfortunately not related to the library. The reason why you could not disable auto rotation `ViewController` is that the rotation behavior is bound to the navigation controller. 

I also faced with issue before with previous project and somehow managed to do it. I'll let you know when I remember the fix.
