### ISSUE TITLE
RTL referencedViewForPhotoAt issue

### ISSUE THREAD

**Issue by a-hasan** [tungvoduc/DTPhotoViewerController#35]
@tungvoduc it's me again with the RTL :)

Could you please have a look on referencedViewForPhotoAt method with the RTL layout.
It returns invalid index,
Thanks again!

**Comment by tungvoduc** [comment]
@a-hasan You seem to like my libraries ;) Thanks for the support.
I will check and fix it asap.

**Comment by a-hasan** [comment]
@tungvoduc yes, they are helpful and valuable libraries :)

**Comment by tungvoduc** [comment]
@a-hasan Everything seems to work fine for me. I am using UICollectionView and it supports RTL layout automatically. Could you please tell me how to reproduce the bug?

**Comment by a-hasan** [comment]
@tungvoduc After DTPhotoViewerController display the selected photo and when the user close 
it to back to the gallery referencedViewForPhotoAt is called with invalid index which cause the returning animation goes to different photo of the selected one .
I think the issue in those lines :
 public var currentPhotoIndex: Int {
        if scrollDirection == .horizontal {
            if scrollView.frame.width == 0 {
                return 0
            }
            **return Int(scrollView.contentOffset.x / scrollView.frame.width)**
        }
        else {
          ....
        }
    }
because with RTL layout first item will be with the offset of last item in case of LTR.

**Comment by tungvoduc** [comment]
@a-hasan Issue fixed in newly released version `3.1.0`.

**Comment by a-hasan** [comment]
@tungvoduc Every thing is working fine now, thanks!
