### ISSUE TITLE
Unable to build with SPM

### ISSUE THREAD

**Issue by danqing** [tungvoduc/DTPhotoViewerController#36]
It looks like the framework comes with SPM support (great!), but when I try to build there are numerous errors. I have several other libraries managed by SPM and they work without an issue...

I'm importing the library via Xcode 11's UI. Also fwiw I can build it just fine with Carthage.

**Comment by tungvoduc** [comment]
@danqing I will check and get back to you asap.

**Comment by danqing** [comment]
I think this is at least partly addressed by #34. Can you merge it?

**Comment by tungvoduc** [comment]
If I remember correctly the deployment target is already iOS 10 so there should not be the check. But I will confirm it.

**Comment by tungvoduc** [comment]
@danqing I am able to add it into my project without any issue using Xcode 11. Can you check it again? Maybe create a test project?

**Comment by tungvoduc** [comment]
@danqing Fixed in version `3.1.1` by adding deployment target.
