### ISSUE TITLE
Problem wit UIStackView

### ISSUE THREAD

**Issue by Urkman** [tungvoduc/DTPhotoViewerController#4]
I build a nice gallery UITableViewCell displaying a vary of Images using UIStackViews.
This works fine and looks good...

But when I now want to show you PhotoViewerController I get some problems :(

That why you simple hide the referenceView.
And when you do this, the UIStackView removes it and updates the constraints.

Any changes to change this to not hide the referenceView?

**Comment by tungvoduc** [comment]
@Urkman : Thanks for your recommendation! I will update the library to support this feature.

**Comment by tungvoduc** [comment]
@Urkman : The feature you requested is now available in latest pod. You just need to set viewer property automaticallyUpdateReferencedViewVisibility = false and the referencedView will not be hidden.

**Comment by Urkman** [comment]
Great... Thanks :)
