### ISSUE TITLE
swift 3 Cannot inherit from non-open class 'DTPhotoCollectionViewCell' outside of its defining module 

### ISSUE THREAD

**Issue by jofax** [tungvoduc/DTPhotoViewerController#6]
"In case you want to add more UI elements to each photo, the best way is to create a subclass of DTPhotoCollectionViewCell and then call either one of these methods registerClassPhotoViewer: or registerNibForPhotoViewer:"

Im using cocoapods, hence I cannot subclassed the DTPhotoCollectionViewCell, error above

**Comment by tungvoduc** [comment]
@jofax : I will make it open class asap. While waiting for the fix, you can use this datasource method as a work around 'photoViewerController(_ photoViewerController: DTPhotoViewerController, configureCell cell: DTPhotoCollectionViewCell, forPhotoAt index: Int)'

**Comment by jofax** [comment]
thanks @tungvoduc
Question: If I use that data source, I will add a custom cell with Nib, is it doable? I tried to add the scroll and the image via Nib but it did it didn't work. Not sure if I did the right way. Can you advice?

thanks

**Comment by tungvoduc** [comment]
@jofax : If you want to provide custom DTPhotoCollectionViewCell by nib, then you need to wait for the new release that makes DTPhotoCollectionViewCell open class. I will publish new release in few hours. If you use cell loaded from nib, your custom cell just needs to subclass DTPhotoCollectionViewCell, then add extra elements you want to the cell.

**Comment by tungvoduc** [comment]
@jofax : I just released new version with updated example, you can see how I add elements to each DTPhotoCollectionViewCell.

**Comment by jofax** [comment]
wow thats fast, thank you @tungvoduc

**Comment by tungvoduc** [comment]
@jofax : Would be nice if you can give me a star.

**Comment by jofax** [comment]
sure! I just added now :)
