### ISSUE TITLE
registerNibForPhotoViewer

### ISSUE THREAD

**Issue by jofax** [tungvoduc/DTPhotoViewerController#7]
Hi Again Tung!

I see that we can register a nib for the cell. But is it customisable? I mean the imageView will be added on the custom cell with Nib.

import UIKit
import DTPhotoViewerController

class TestPhotoCell: DTPhotoCollectionViewCell {
    
    @IBOutlet var lblTest: UILabel!
    @IBOutlet var imageView: UIImageView!

    override func layoutSubviews() {
        super.layoutSubviews()
        //should layout those label and imageView!
    }

**Comment by tungvoduc** [comment]
@jofax : Sorry for late reply, DTPhotoViewerController is designed to support how the viewer should work and be expected to work. But anyway, you can customise layoutSubviews how you want after calling super.layoutSubviews().
