### ISSUE TITLE
photoViewerController: referencedViewForPhotoAt: never call

### ISSUE THREAD

**Issue by oniikal3** [tungvoduc/DTPhotoViewerController#8]
other methods in datasource called except "referencedViewForPhotoAt". I don't know why.

**Comment by oniikal3** [comment]
Sorry, First question is my fault because I set numberOfItems = 1. but after I tried more than 1. it will call when I scroll to next photo. As I see in example. it should call when user click close or swipe down to close a viewer. is that a bug?

**Comment by tungvoduc** [comment]
@oniikal3 : This is my intention, we need to know the referenced view when you close the viewer controller so it will make a nicer transition.

**Comment by oniikal3** [comment]
I mean it should call when close the viewer controller. But for me it call whenever I swipe left/right to the next/previous images. 

Thanks for your response

**Comment by tungvoduc** [comment]
@oniikal3 : Yes, it should and I actually fixed that some time ago but I haven't published new version. I will do that asap.

**Comment by oniikal3** [comment]
Ok cool. Thanks :)

**Comment by tungvoduc** [comment]
@oniikal3: I just released new version. Please check :)
