### ISSUE TITLE
Delegate and datasource use in UIViewController Class

### ISSUE THREAD

**Issue by ErAshu** [tungvoduc/DTPhotoViewerController#9]
How can i get the delegate response in UiViewController class?
See my code here, I want to add cancel button on the top of the left corner. I am using `BDFPostPhotoViewerController.swift` file. 

Here is my **Image Tapped Function** where i initialise the class, i want to show/hide cross button on corner  when image zoom or zoom out.

![screen shot 2017-08-04 at 4 18 49 pm](https://user-images.githubusercontent.com/4178384/28965822-a9db51a0-7930-11e7-9ad0-be3bc62e2787.png)

i tried to use like this but here is some error. See screenshot
![screen shot 2017-08-04 at 4 50 31 pm](https://user-images.githubusercontent.com/4178384/28966683-40ef03f8-7935-11e7-9076-e3a9f3f17525.png)

**Please help me. Thanks**

**Comment by tungvoduc** [comment]
@ErAshu You just need to implement the required methods from delegate and datasource. If you are not displaying multiple photos, then you don't need to conform DTPhotoViewerControllerDataSource. If you want to do some actions when zooming in or out on image, you can override these methods: **willZoomOnPhoto(at index: Int)** or **didEndZoomingOnPhoto(at index: Int, atScale scale: CGFloat)**

**Comment by ErAshu** [comment]
When i tried to implement delegate method, see the screenshot. An error occurred. How i can implement this? I am not displaying the multiple photos. I am using UIViewController class. Simple on image tap, a method will call and image will zoom. Its working as expecting but only cross / close icon not showing as expected. 
Method is displaying in screenshot. You can see in screenshot above.

**Comment by tungvoduc** [comment]
@ErAshu I just updated the library and sample project. Can you download and check it again? And please remember to pod update DTPhotoViewerController to get the latest version.

**Comment by ErAshu** [comment]
**Thanks** a lot Bro... Now its working fine.
